### ISSUE TITLE
代码编译报错

### ISSUE THREAD

**Issue by ImJoyed** [MscBaiMeow/FishBot#1]
想在linux下编译然后运行在云服务器上，没接触过Go语言，有个报错查不出来怎么解决，希望帮忙

错误信息：go: github.com/AlecAivazis/survey/v2@v2.0.4 used for two different module paths (github.com/AlecAivazis/survey and github.com/AlecAivazis/survey/v2)
编译环境：CentOS 7.4 x64 go1.13.1 Linux/amd64

**Comment by BaiMeow** [comment]
关于survey这个包，我也有点迷，抱歉暂时帮不上
