### ISSUE TITLE
无法解析服务器

### ISSUE THREAD

**Issue by CberYellowstone** [MscBaiMeow/FishBot#2]
有的服务器解析不了
mc.doubicraft.cn 1.14.4的
zth.ria.red 1.13.2的
但是别的就行
play.minemc.cn 全版本

下面放出日志
autofish-1.13.exe -offline-mode -name CBYellowstone -ip zth.ria.red
2020/01/29 15:25:31 自动钓鱼机器人启动！
2020/01/29 15:25:31 基于github.com/Tnze/gomcbot
2020/01/29 15:25:31 作者: Tnze
2020/01/29 15:25:31 -h参数以查看更多用法
2020/01/29 15:25:31 加入服务器zth.ria.red:25565失败: cannot connect the server "zth.ria.red": dial tcp: lookup zth.ria.red: no such host

我保证端口没输错,这个服务器也是真实能上去的
防火墙也是开放规则的
为什么就连不上????

**Comment by BaiMeow** [comment]
zth的服我试过可以的啊

**Comment by BaiMeow** [comment]
当时加入超时那个参数就是因为zth的服钓鱼tps太低了

**Comment by BaiMeow** [comment]
我有空会再试试的

**Comment by BaiMeow** [comment]
这俩服都是SRV解析的，安排一下
`nslookup -q=srv _minecraft._tcp.mc.doubicraft.cn`
但实际上最新的钓鱼机器人会自动进行SRV解析
