### ISSUE TITLE
钓鱼竿会漂浮走的问题

### ISSUE THREAD

**Issue by ENTNEAZ** [MscBaiMeow/FishBot#3]
如果在公开水域钓鱼的话，扔出的钓鱼竿会漂浮到落水点一格以外的地方，
建议把 AutoFish.go 第143行的 < 1 改大
(亲测<5能工作，但是不是大了点)

**Comment by BaiMeow** [comment]
这个有些服务器有，有些服务器没有，我自己服务器上<0.2既可以工作了，貌似是跨版本插件的锅
至于<5确实过大，多开钓鱼容易互相干扰（当初要读浮漂坐标就是为了多开钓鱼
我现在还没想好要怎么搞

**Comment by BaiMeow** [comment]
改成鱼饵竖直方向运动判定是否上钩不再考虑水平距离
