### ISSUE TITLE
无法输入ip

### ISSUE THREAD

**Issue by lingyunQAQ** [MscBaiMeow/FishBot#6]
D:\桌面>AutoFish -ip 221.131.165.84
2020/03/28 14:58:18 自动钓鱼机器人启动！
2020/03/28 14:58:18 机器人版本：1.5.0
2020/03/28 14:58:18 游戏版本：1.15.2
2020/03/28 14:58:18 基于github.com/Tnze/go-mc
2020/03/28 14:58:18 作者: Tnze＆BaiMeow
2020/03/28 14:58:18 -h参数以查看更多用法
2020/03/28 14:58:18 配置文件不存在，请使用-account参数添加open ./conf.json: The system cannot find the file specified.

**Comment by BaiMeow** [comment]
麻烦你打个-account加个账户给他登陆
