### ISSUE TITLE
挂机时间久了会饿死

### ISSUE THREAD

**Issue by chinese-wzq** [MscBaiMeow/FishBot#7]
建议增加自动吃食物的功能，如果食物吃完饥饿度不足自动下线以免饿死，昨晚挂机活生生饿死了QAQ

**Comment by chinese-wzq** [comment]
还有要实时监测生命度是否低于某个值，如果低于就自动下线，可以有效避免死亡。

**Comment by BaiMeow** [comment]
站着不动是不会掉饱食度的,避免死亡意义不大

**Comment by chinese-wzq** [comment]
可是避免死亡的机制也是比较有必要的，毕竟你永远不知道挂机一个晚上会不会有怪物进你家炸你
