### ISSUE TITLE
部分服务器密码输入正确加入时报错

### ISSUE THREAD

**Issue by chinese-wzq** [MscBaiMeow/FishBot#8]
部分服务器密码输入正确加入时报错，报错内容：

bot: encryption fail: login fail: auth fail:

**Comment by chinese-wzq** [comment]
如ms4.nide8.com:25566

**Comment by chinese-wzq** [comment]
而且之前试了几次都不会报错，最近才开始报错。

**Comment by BaiMeow** [comment]
连不上你所说的服务器
